- hosts: ios
  gather_facts: no
  connection: network_cli
  tasks:
    - include_role:
        name: network-backup
      vars:
        network_backup_repository: 'git@github.com:colin-mccarthy/ansible_network_backups.git'
